version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.1.0

workflows:
  build_and_push_image:
    jobs:
      push-app-service:
        steps:
          - aws-ecr/build-and-push-image:
              create-repo: true
              dockerfile: infrastructure/docker/php/Dockerfile
              path: .
              repo: laravel-ecs-app
      push-web-service:
        steps:
          - aws-ecr/build-and-push-image:
              create-repo: true
              dockerfile: infrastructure/docker/nginx/Dockerfile
              path: .
              repo: laravel-ecs-web
      - aws-ecs/deploy-service-update:
          cluster-name: "${MY_APP_PREFIX}-cluster"
          container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}"
          family: "${MY_APP_PREFIX}-service"
          requires:
            - push-app-service
            - push-web-service
