version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.15
  aws-ecs: circleci/aws-ecs@2.1.0

workflows:
  build-and-deploy:
    jobs:
      - aws-ecr/build-and-push-image:
          name: push-app-service
          create-repo: true
          dockerfile: infrastructure/docker/php/Dockerfile
          path: .
          repo: laravel-ecs-app
      - aws-ecr/build-and-push-image:
          name: push-web-service
          create-repo: true
          dockerfile: infrastructure/docker/nginx/Dockerfile
          path: .
          repo: laravel-ecs-web
      - aws-ecs/deploy-service-update:
          requires:
            - push-app-service
            - push-web-service
          cluster-name: "${MY_APP_PREFIX}-cluster"
          container-image-name-updates: "container=${MY_APP_PREFIX}-service,tag=${CIRCLE_SHA1}"
          family: "${MY_APP_PREFIX}-service"
